source/documentation/index.md

Fixing email link errors, plus language edits.

CTDA-288 content edits, markdown changes

---

source/documentation/index.md

Updated diagram link

---

source/documentation/index.md

Deleting as on off-shoot page.

CTDA-228 movements diagram content

---

config/tech-docs.yml

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-893)

Updated links

---

README.md
source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1058)

CTDA-1058/update-service-guide-content

---

source/documentation/index.md

[Requested changes](https://docs.google.com/document/d/1jONNy6-f7Vt6NDkSz5sdKTlB3gwjjk8LzYjJYG8XFoQ/edit#)
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1058)

CTDA-1058/service guide content fixes

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1058)

CTDA 1058 - Changed path to images

---

build.sbt
config/tech-docs.yml
project/plugins.sbt
source/documentation/arrivals-diagram.html.md.erb
source/documentation/end-to-end-happy-path.html.md.erb
source/documentation/get-support.html.md.erb
source/documentation/partials/_google_tag_manager_js.html.erb
source/documentation/supported-messages.html.md.erb
source/documentation/xsd-reference.html.md.erb
source/index.html.md.erb

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1130)

CTDA-1130/Changed Google tags 

---

source/documentation/partials/_google_tag_manager_js.html.erb

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1130)

CTDA-1130/cookie-consent

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1146)

Ctda 1146/remove test support refs

---

source/documentation/index.md
source/documentation/questions-and-answers.html.md.erb

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1163)

Ctda 1163/questions and answers

---

source/documentation/questions-and-answers.html.md.erb

This is content updates from the original Q&A ticket.
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1163)

Content updates

---

source/documentation/questions-and-answers.html.md.erb

Changes to link

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1179)
[Subtask](https://jira.tools.tax.service.gov.uk/browse/CTDA-1244)

Ctda 1179/hyperlink to testing guide

---

source/documentation/index.md

[Ticket](https://github.com/hmrc/common-transit-convention-traders-roadmap/pull/70)

Ctda 1231/go live content

---

.gitignore
source/documentation/index.md

[ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1258)

CTDA-1258/tt-for-ni

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1404)

Ctda 1404/go live and ni mentions

---

source/documentation/index.md
source/documentation/xsd-reference.html.md.erb

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1358)

CTDA-1358/new-917-xsd

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1395)

CTDA-1395/cap and filter

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1534)

CTDA-1534/push pull updates

---

source/documentation/index.md

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1564)

CTDA-1564/MesSenMES3 info
